export const GET_APPOINTMENT_FETCHING = "GET_APPOINTMENT_FETCHING";
export const GET_APPOINTMENT_FULFILLED = "GET_APPOINTMENT_FULFILLED";
export const GET_APPOINTMENT_REJECTED = "GET_APPOINTMENT_REJECTED";

export const ADD_APPOINTMENT_FETCHING = "ADD_APPOINTMENT_FETCHING";
export const ADD_APPOINTMENT_FULFILLED = "ADD_APPOINTMENT_FULFILLED";
export const ADD_APPOINTMENT_REJECTED = "ADD_APPOINTMENT_REJECTED";

export const DELETE_APPOINTMENT_FETCHING = "DELETE_APPOINTMENT_FETCHING";
export const DELETE_APPOINTMENT_FULFILLED = "DELETE_APPOINTMENT_FULFILLED";
export const DELETE_APPOINTMENT_REJECTED = "DELETE_APPOINTMENT_REJECTED";

export const UPDATE_APPOINTMENT_FETCHING = "UPDATE_APPOINTMENT_FETCHING";
export const UPDATE_APPOINTMENT_FULFILLED = "UPDATE_APPOINTMENT_FULFILLED";
export const UPDATE_APPOINTMENT_REJECTED = "UPDATE_APPOINTMENT_REJECTED";
