export const GET_APPOINTMENTS_FETCHING = "GET_APPOINTMENTS_FETCHING";
export const GET_APPOINTMENTS_FULFILLED = "GET_APPOINTMENTS_FULFILLED";
export const GET_APPOINTMENTS_REJECTED = "GET_APPOINTMENTS_REJECTED";

export const ADD_APPOINTMENTS_FETCHING = "ADD_APPOINTMENTS_FETCHING";
export const ADD_APPOINTMENTS_FULFILLED = "ADD_APPOINTMENTS_FULFILLED";
export const ADD_APPOINTMENTS_REJECTED = "ADD_APPOINTMENTS_REJECTED";

export const DELETE_APPOINTMENTS_FETCHING = "DELETE_APPOINTMENTS_FETCHING";
export const DELETE_APPOINTMENTS_FULFILLED = "DELETE_APPOINTMENTS_FULFILLED";
export const DELETE_APPOINTMENTS_REJECTED = "DELETE_APPOINTMENTS_REJECTED";

export const UPDATE_APPOINTMENTS_FETCHING = "UPDATE_APPOINTMENTS_FETCHING";
export const UPDATE_APPOINTMENTS_FULFILLED = "UPDATE_APPOINTMENTS_FULFILLED";
export const UPDATE_APPOINTMENTS_REJECTED = "UPDATE_APPOINTMENTS_REJECTED";