export const GET_BOILERS_FETCHING = "GET_BOILERS_FETCHING";
export const GET_BOILERS_FULFILLED = "GET_BOILERS_FULFILLED";
export const GET_BOILERS_REJECTED = "GET_BOILERS_REJECTED";

export const ADD_BOILER_FETCHING = "ADD_BOILER_FETCHING";
export const ADD_BOILER_FULFILLED = "ADD_BOILER_FULFILLED";
export const ADD_BOILER_REJECTED = "ADD_BOILER_REJECTED";

export const DELETE_BOILER_FETCHING = "DELETE_BOILER_FETCHING";
export const DELETE_BOILER_FULFILLED = "DELETE_BOILER_FULFILLED";
export const DELETE_BOILER_REJECTED = "DELETE_BOILER_REJECTED";

export const EDIT_BOILER_FETCHING = "EDIT_BOILER_FETCHING";
export const EDIT_BOILER_FULFILLED = "EDIT_BOILER_FULFILLED";
export const EDIT_BOILER_REJECTED = "EDIT_BOILER_REJECTED";