export const GET_BOILERS_TYPES_FETCHING = "GET_BOILERS_TYPES_FETCHING";
export const GET_BOILERS_TYPES_FULFILLED = "GET_BOILERS_TYPES_FULFILLED";
export const GET_BOILERS_TYPES_REJECTED = "GET_BOILERS_TYPES_REJECTED";

export const ADD_BOILER_TYPE_FETCHING = "ADD_BOILER_TYPE_FETCHING";
export const ADD_BOILER_TYPE_FULFILLED = "ADD_BOILER_TYPE_FULFILLED";
export const ADD_BOILER_TYPE_REJECTED = "ADD_BOILER_TYPE_REJECTED";

export const DELETE_BOILER_TYPE_FETCHING = "DELETE_BOILER_TYPE_FETCHING";
export const DELETE_BOILER_TYPE_FULFILLED = "DELETE_BOILER_TYPE_FULFILLED";
export const DELETE_BOILER_TYPE_REJECTED = "DELETE_BOILER_TYPE_REJECTED";

export const EDIT_BOILER_TYPE_FETCHING = "EDIT_BOILER_TYPE_FETCHING";
export const EDIT_BOILER_TYPE_FULFILLED = "EDIT_BOILER_TYPE_FULFILLED";
export const EDIT_BOILER_TYPE_REJECTED = "EDIT_BOILER_TYPE_REJECTED";