  
export const ADD_BOILER = "ADD_BOILER";
export const DELETE_BOILER = "DELETE_BOILER";
export const EDIT_BOILER = "EDIT_BOILER";
export const GET_BOILERS_FETCHING = "GET_BOILERS_FETCHING";
export const GET_BOILERS_FULFILLED = "GET_BOILERS_FULFILLED";
export const GET_BOILERS_REJECTED = "GET_BOILERS_REJECTED";

