export const GET_CUSTOMERS_FETCHING = "GET_CUSTOMERS_FETCHING";
export const GET_CUSTOMERS_FULFILLED = "GET_CUSTOMERS_FULFILLED";
export const GET_CUSTOMERS_REJECTED = "GET_CUSTOMERS_REJECTED";

export const ADD_CUSTOMER_FETCHING = "ADD_CUSTOMER_FETCHING";
export const ADD_CUSTOMER_FULFILLED = "ADD_CUSTOMER_FULFILLED";
export const  ADD_CUSTOMER_REJECTED = "ADD_CUSTOMER_REJECTED";

export const DELETE_CUSTOMER_FETCHING = "DELETE_CUSTOMER_FETCHING";
export const DELETE_CUSTOMER_FULFILLED = "DELETE_CUSTOMER_FULFILLED";
export const DELETE_CUSTOMER_REJECTED = "DELETE_CUSTOMER_REJECTED";

export const UPDATE_CUSTOMER_FETCHING = "UPDATE_CUSTOMER_FETCHING";
export const UPDATE_CUSTOMER_FULFILLED = "UPDATE_CUSTOMER_FULFILLED";
export const UPDATE_CUSTOMER_REJECTED = "UPDATE_CUSTOMER_REJECTED";
