export const GET_CUSTOMERS_FETCHING = "GET_CUSTOMERS_FETCHING";
export const GET_CUSTOMERS_FULFILLED = "GET_CUSTOMERS_FULFILLED";
export const GET_CUSTOMERS_REJECTED = "GET_CUSTOMERS_REJECTED";

export const ADD_CUSTOMER_FETCHING = "ADD_CUSTOMER_FETCHING";
export const ADD_CUSTOMER_FULFILLED = "ADD_CUSTOMER_FULFILLED";
export const  ADD_CUSTOMER_REJECTED = "ADD_CUSTOMER_REJECTED";

export const DELETE_CUSTOMER_FETCHING = "DELETE_CUSTOMER_FETCHING";
export const DELETE_CUSTOMER_FULFILLED = "DELETE_CUSTOMER_FULFILLED";
export const DELETE_CUSTOMER_REJECTED = "DELETE_CUSTOMER_REJECTED";

export const EDIT_CUSTOMER_FETCHING = "EDIT_CUSTOMER_FETCHING";
export const EDIT_CUSTOMER_FULFILLED = "EDIT_CUSTOMER_FULFILLED";
export const EDIT_CUSTOMER_REJECTED = "EDIT_CUSTOMER_REJECTED";
