export const GET_CUSTOMER_FETCHING = 'GET_CUSTOMER_FETCHING'
export const GET_CUSTOMER_FULFILLED = 'GET_CUSTOMER_FULFILLED'
export const GET_CUSTOMER_REJECTED = 'GET_CUSTOMER_REJECTED'

export const ADD_CUSTOMER_FETCHING = "ADD_CUSTOMER_FETCHING";
export const ADD_CUSTOMER_FULFILLED = "ADD_CUSTOMER_FULFILLED";
export const ADD_CUSTOMER_REJECTED = "ADD_CUSTOMER_REJECTED";

export const DEL_CUSTOMER_FETCHING = "DEL_CUSTOMER_FETCHING";
export const DEL_CUSTOMER_FULFILLED = "DEL_CUSTOMER_FULFILLED";
export const DEL_CUSTOMER_REJECTED = "DEL_CUSTOMER_REJECTED";

export const UPD_CUSTOMER_FETCHING = "UPD_CUSTOMER_FETCHING";
export const UPD_CUSTOMER_FULFILLED = "UPD_CUSTOMER_FULFILLED";
export const UPD_CUSTOMER_REJECTED = "UPD_CUSTOMER_REJECTED";