export const GET_TECHNICIANS_FETCHING = "GET_TECHNICIANS_FETCHING";
export const GET_TECHNICIANS_FULLFILLED = "GET_TECHNICIANS_FULLFILLED";
export const GET_TECHNICIANS_REJECTED = "GET_TECHNICIANS_REJECTED";

export const ADD_TECH_FETCHING = "ADD_TECH_FETCHING";
export const ADD_TECH_FULLFILLED = "ADD_TECH_FULLFILLED";
export const ADD_TECH_REJECTED = "ADD_TECH_REJECTED";

export const DELETE_TECH_FETCHING = "DELETE_TECH_FETCHING";
export const DELETE_TECH_FULLFILLED = "DELETE_TECH_FULLFILLED";
export const DELETE_TECH_REJECTED = "DELETE_TECH_REJECTED";

export const UPDATE_TECH_FETCHING = "UPDATE_TECH_FETCHING";
export const UPDATE_TECH_FULLFILLED = "UPDATE_TECH_FULLFILLED";
export const UPDATE_TECH_REJECTED = "UPDATE_TECH_REJECTED";